export const tourStops = [
  {
    id: 'museum',
    label: 'Museum',
    markerClass: 'feature-scene__route-stop--museum',
  },
  {
    id: 'market',
    label: 'Market',
    markerClass: 'feature-scene__route-stop--market',
  },
  {
    id: 'bridge',
    label: 'Bridge',
    markerClass: 'feature-scene__route-stop--bridge',
  },
  {
    id: 'park',
    label: 'Park',
    markerClass: 'feature-scene__route-stop--park',
  },
  {
    id: 'theater',
    label: 'Theater',
    markerClass: 'feature-scene__route-stop--theater',
  },
];

export const streetLayouts = [
  {
    nodes: {
      'stop-nw': { x: 12, y: 23 },
      'north-center': { x: 49, y: 18 },
      'stop-ne': { x: 88, y: 24 },
      'west-cross': { x: 16, y: 49 },
      'center-cross': { x: 47, y: 46 },
      'east-cross': { x: 84, y: 52 },
      'stop-center': { x: 52, y: 64 },
      'stop-sw': { x: 13, y: 80 },
      'south-west': { x: 31, y: 76 },
      'south-center': { x: 52, y: 82 },
      'south-east': { x: 73, y: 78 },
      'stop-se': { x: 88, y: 80 },
    },
    edges: [
      ['stop-nw', 'north-center'],
      ['north-center', 'stop-ne'],
      ['stop-nw', 'west-cross'],
      ['west-cross', 'stop-sw'],
      ['stop-ne', 'east-cross'],
      ['east-cross', 'stop-se'],
      ['west-cross', 'center-cross'],
      ['center-cross', 'east-cross'],
      ['center-cross', 'stop-center'],
      ['stop-sw', 'south-west'],
      ['south-west', 'south-center'],
      ['south-center', 'south-east'],
      ['south-east', 'stop-se'],
      ['stop-center', 'south-center'],
    ],
    paths: [
      ['stop-nw', 'north-center', 'stop-ne'],
      ['stop-nw', 'west-cross', 'stop-sw'],
      ['stop-ne', 'east-cross', 'stop-se'],
      ['west-cross', 'center-cross', 'east-cross'],
      ['stop-sw', 'south-west', 'south-center', 'south-east', 'stop-se'],
      ['center-cross', 'stop-center', 'south-center'],
    ],
  },
  {
    nodes: {
      'stop-nw': { x: 14, y: 18 },
      'north-center': { x: 44, y: 28 },
      'stop-ne': { x: 86, y: 16 },
      'west-cross': { x: 20, y: 43 },
      'center-cross': { x: 53, y: 48 },
      'east-cross': { x: 82, y: 42 },
      'stop-center': { x: 42, y: 62 },
      'stop-sw': { x: 12, y: 84 },
      'south-west': { x: 34, y: 74 },
      'south-center': { x: 58, y: 83 },
      'south-east': { x: 76, y: 70 },
      'stop-se': { x: 90, y: 84 },
    },
    edges: [
      ['stop-nw', 'north-center'],
      ['north-center', 'stop-ne'],
      ['stop-nw', 'west-cross'],
      ['west-cross', 'south-west'],
      ['south-west', 'stop-sw'],
      ['stop-ne', 'east-cross'],
      ['east-cross', 'south-east'],
      ['south-east', 'stop-se'],
      ['west-cross', 'center-cross'],
      ['center-cross', 'east-cross'],
      ['center-cross', 'stop-center'],
      ['stop-center', 'south-west'],
      ['stop-center', 'south-center'],
      ['south-west', 'south-center'],
      ['south-center', 'south-east'],
    ],
    paths: [
      ['stop-nw', 'north-center', 'stop-ne'],
      ['stop-nw', 'west-cross', 'south-west', 'stop-sw'],
      ['stop-ne', 'east-cross', 'south-east', 'stop-se'],
      ['west-cross', 'center-cross', 'east-cross'],
      ['stop-center', 'south-west', 'south-center', 'south-east'],
      ['center-cross', 'stop-center', 'south-center'],
    ],
  },
  {
    nodes: {
      'stop-nw': { x: 10, y: 27 },
      'north-center': { x: 39, y: 20 },
      'stop-ne': { x: 90, y: 29 },
      'west-cross': { x: 17, y: 57 },
      'center-cross': { x: 50, y: 42 },
      'east-cross': { x: 83, y: 57 },
      'stop-center': { x: 57, y: 66 },
      'stop-sw': { x: 16, y: 82 },
      'south-west': { x: 36, y: 86 },
      'south-center': { x: 50, y: 76 },
      'south-east': { x: 70, y: 88 },
      'stop-se': { x: 86, y: 82 },
    },
    edges: [
      ['stop-nw', 'north-center'],
      ['north-center', 'center-cross'],
      ['center-cross', 'stop-ne'],
      ['stop-nw', 'west-cross'],
      ['west-cross', 'stop-sw'],
      ['stop-ne', 'east-cross'],
      ['east-cross', 'stop-se'],
      ['west-cross', 'center-cross'],
      ['center-cross', 'east-cross'],
      ['center-cross', 'stop-center'],
      ['stop-center', 'south-center'],
      ['stop-sw', 'south-west'],
      ['south-west', 'south-center'],
      ['south-center', 'south-east'],
      ['south-east', 'stop-se'],
    ],
    paths: [
      ['stop-nw', 'north-center', 'center-cross', 'stop-ne'],
      ['stop-nw', 'west-cross', 'stop-sw'],
      ['stop-ne', 'east-cross', 'stop-se'],
      ['west-cross', 'center-cross', 'east-cross'],
      ['stop-center', 'south-center'],
      ['stop-sw', 'south-west', 'south-center', 'south-east', 'stop-se'],
    ],
  },
];

export const markerPlacementRules = {
  minimumSpacing: 22,
  minimumXRange: 48,
  minimumYRange: 34,
};
